web/router.ex
defmodule Eecrit.Router do
  use Eecrit.Web, :router
  import Eecrit.SessionPlugs, only: [add_current_user: 2,
                                     v2_add_current_user: 2,
                                     require_login: 2,
                                     require_admin: 2,
                                     require_superuser: 2]
  import Eecrit.SinglePageAppPlugs, only: [default_to_no_single_page_app: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :add_current_user
    plug :v2_add_current_user
    plug :default_to_no_single_page_app
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/v2", Eecrit do 
    pipe_through [:browser]

    get "/", V2PageController, :index
    get "/about", V2PageController, :about
    get "/experiment", V2PageController, :experiment
    resources "/sessions", V2SessionController, only: [:delete]
    get "/animals/*rest", AnimalController, :all
    post "/log_in_demo_user", V2SessionController, :log_in_demo_user
    get "/unfinished", UnfinishedController, :index

    get "/*path", ElmController, :choose_page
  end  

  # TODO: I'm not sure where to store the fact that a user must have
  # ability X to access resource Y. Should it be here, to give a broad
  # overview? Or should it be attached to the resource (which would make
  # sense for finer-granularity permissions)?
  #
  # A related issue: we need not only to prevent a pipeline from delivering
  # the user to a page, we also need views to not display links to that page.
  # So it's more than just about controllers.
  

  # Not-logged-in users
  scope "/", Eecrit do
    pipe_through :browser

    get "/", PageController, :index
    get "/help", HelpController, :index
    # TODO: Remove this when more comfortable with embedding Elm
    get "/elm", ElmController, :index
    get "/iv/*path", IVController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Only for logged-in users
  scope "/", Eecrit do
    pipe_through [:browser, :require_login]
  end

  # Controllers that require Admin permissions.
  scope "/", Eecrit do
    pipe_through [:browser, :require_login, :require_admin]

    resources "/animals", OldAnimalController
    resources "/procedures", OldProcedureController
    resources "/procedure_descriptions", OldProcedureDescriptionController

    scope "/reports" do
      get "/animal-use", ReportController, :animal_use
      post "/animal-use", ReportController, :animal_use
      get "/animal-reservations", ReportController, :animal_reservations
    end
  end

  # Controllers that require superuser permissions.
  scope "/", Eecrit do
    pipe_through [:browser, :require_login, :require_superuser]

    resources "/users", UserController
    resources "/ability_groups", AbilityGroupController
    resources "/organizations", OrganizationController
  end

  scope "/api", Eecrit do
    pipe_through :api
    
    resources "/animals", OldAnimalApiController, only: [:index]

    # Todo: how to do all the rest fakery from elm - if it's worth it
    post "/v2animals/create/:original_id", AnimalApiController, :create
    get "/v2animals", AnimalApiController, :index
    post "/v2animals", AnimalApiController, :update
    get "/v2animals/:id/history", AnimalApiController, :history
  end
end

web/views/layout_view.ex
defmodule Eecrit.LayoutView do
  use Eecrit.Web, :view
  import Eecrit.Router.Helpers

  # use Eecrit.Helpers.Tags
  alias Eecrit.Helpers.Tags
  import Eecrit.Helpers.Aggregates
  alias Eecrit.Helpers.Logical
  alias Eecrit.Helpers.Bootstrap
  import Eecrit.ControlFlow
  alias Eecrit.Helpers.Bulma
  alias Plug.Conn

  # TODO: Have so far been unable to use a V2LayoutView - it's not available
  # when template is compiled.

  @home "Home"
  @about "About"

  defp handler_to_tab_name(conn) do
    case {Controller.controller_module(conn), Controller.action_name(conn)} do
      {Eecrit.V2PageController, :index} -> @home
      {Eecrit.V2PageController, :about} -> @about
      _ -> :not_relevant_to_navigation_bar
    end
  end

  def tab_item_options(conn, name) do
    [on_page_signified_by_tab: handler_to_tab_name(conn) == name]
  end

  defp tab_item(conn, name, path),
    do: Bulma.tab_item(name, path, tab_item_options(conn, name))

  defp maybe_home(so_far, conn) do
    list_augment_if conn.assigns.v2_current_user, so_far do
      tab_item(conn, @home, v2_page_path(conn, :index))
    end
  end

  defp maybe_about(so_far, conn) do
    always_present = tab_item(conn, @about, v2_page_path(conn, :about))
    [always_present | so_far]
  end

  defp maybe_logout(so_far, conn) do
    current_user = conn.assigns.v2_current_user
    list_augment_if current_user, so_far do
      Bulma.tab_button("Log out", v2_session_path(conn, :delete, current_user),
        method: :delete)
    end
  end

  def navbar_items(conn) do
    []
    |> maybe_home(conn)
    |> maybe_about(conn)
    |> maybe_logout(conn)
    |> Enum.reverse
  end

  defp v2_user_description(conn) do
    if conn.assigns.v2_current_user do
      "Trial User at Demo U"
    else
      ""
    end
  end
  
  def v2_default_layout(conn, _opts) do
    layout_data = 
      %{left_picture_path: v2_page_path(conn, :index),
        user: v2_user_description(conn),
        links: navbar_items(conn)
       }

    conn
    |> Controller.put_layout("v2_layout_default.html")
    |> Conn.assign(:layout_data, layout_data)
  end


  defp one_flash(conn, color, key) do
    flash = Controller.get_flash(conn, key)
    list_if flash do
      Tags.nav class: "notification #{color}" do
        flash
      end
    end
  end

  def v2_flash(conn) do
    [one_flash(conn, "is-success", :success),
     one_flash(conn, "is-info", :info), 
     one_flash(conn, "is-danger", :error),
    ]
  end


  #######
  ######## The below is all for *V1*
  #######
  
  use Eecrit.TagHelpers
  alias Eecrit.AggregateViewWidgets

  def navigation(conn) do
    iolists = [
      link("Home", to: page_path(conn, :index)),
      AggregateViewWidgets.reports_launcher(conn),
      m_resource_link(conn, "Animals", Eecrit.OldAnimal),
      m_resource_link(conn, "Procedures", Eecrit.OldProcedure),
      salutation(conn),
      organization(conn),
      log_in_out(conn),
    ]

    Enum.map(iolists, &li/1)
  end

  def log_in_out(conn) do
    current_user = conn.assigns.current_user
    if current_user == nil do
      link("Log in", to: session_path(conn, :new))
    else
      link("Log out", to: session_path(conn, :delete, current_user), method: "delete")
    end
  end
    
  def salutation(conn) do
    current_user = conn.assigns.current_user
    list_if current_user, do: current_user.display_name
  end

  def organization(conn) do
    current_user = conn.assigns.current_user
    list_if current_user, do: current_user.current_organization.short_name
  end

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Veterinary medicine application">
    <meta name="author" content="Brian Marick">

    <title>Critter4Us</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ol class="breadcrumb text-right">
            <%= navigation(@conn) %> 
          </ol>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= Controller.get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= Controller.get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/c4u.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Veterinary medicine application">
    <meta name="author" content="Brian Marick">

    <title>Critter4Us</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.2.3/css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

<body>
  <nav class="nav has-shadow" id="top">
    <div class="container">
      <div class="nav-left" style="overflow-x: hidden">
        <a class="nav-item" href="../index.html">
          <img src="../images/critter4us.png" alt="Critter4Us">
        </a>
        <!-- <span class="nav-item" style="overflow-x: hidden">Somebody Something at Placething</span> -->
      </div>
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>
      <div class="nav-right nav-menu">
        <!-- <a class="nav-item is-tab is-active"> -->
        <!--   Home -->
        <!-- </a> -->
        <!-- <a class="nav-item is-tab"> -->
        <!--   Features -->
        <!-- </a> -->
        <!-- <a class="nav-item is-tab"> -->
        <!--   Team -->
        <!-- </a> -->
        <a class="nav-item is-tab">
          Help
        </a>

        <span class="nav-item">
          <form action="/sessions/4" method="post">
            <input name="_method" type="hidden" value="delete">
            <input name="_csrf_token" type="hidden" value="JBxGTxkhJX09aUM+IjEVNwQHFF8jEAAAbPi+AtgRE+5sMuDRLfFmjg==">
            <a class="button" data-submit="parent" href="#" rel="nofollow">
              Log in
            </a>
          </form>
          
          <!-- <a class="button is-info" style="margin-left: 10px;"> -->
          <!--   Try it out -->
          <!-- </a> -->
        </span>
      </div>
    </div>
  </nav>
  <section class="section">
    <div class="container content">
      <p class="has-text-centered">
        Critter4Us is a blah, blah, blah. 
      </p>
      <p class="has-text-centered">
        You may look at sample data with login "demo" and password "louis".
        <br/>
        <a href="#">Try it now</a>
      </p>


      <p class="has-text-centered">
        In order to try out managing animals and making reservations, you'll need a
        <br/>
        <a href="#">Trial account</a>
      </p>

      
    </div>
  </section>
  <script>window.auth_token = "<%= assigns[:auth_token] %>"</script>
  <script>window.socket_uri = "<%= Eecrit.Endpoint.socket_uri %>"</script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>

web/templates/layout/iv.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Veterinary medicine application">
    <meta name="author" content="Brian Marick">

    <title>IV Drip Worksheet</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/v2_layout_default.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Teaching animal reservation system">
    <meta name="author" content="Brian Marick">

    <title>Critter4Us</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.2.3/css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/elm-date-selector.css">
    
  </head>
  <body>
    <div class="container">
      <nav class="nav has-shadow" id="top">
        <div class="nav-left" style="overflow-x: hidden">
          <a class="nav-item" href="<%= assigns.layout_data.left_picture_path %>">
            <img src="/images/critter4us.png" alt="Critter4Us">
          </a>
          <span class="nav-item" style="overflow-x: hidden">
            <%= assigns.layout_data.user  %>
          </span>
        </div>
        <span class="nav-toggle">
          <span></span>
          <span></span>
          <span></span>
        </span>
        <div class="nav-right nav-menu">
          <%= Enum.map(assigns.layout_data.links, &raw/1) %>
        </div>
      </nav>
      <%= v2_flash(@conn) %>
      <%= render @view_module, @view_template, assigns %>
  
    </div>

    <footer class="footer">
      <div class="level">
        <p class="level-item has-text-centered">
            Copyright © 2017 Brian Marick
        </p>
        <p class="level-item has-text-centered">
          <%= Eecrit.Version.version %>
        </p>
        <p class="level-item has-text-centered">
          <a href="<%= unfinished_path(@conn, :index)%>">
            Terms and Disclaimer
          </a>
        </p>
      </div>
    </footer>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  <%= @eecrit_spa_launcher %>
</body>
</html>