web/router.ex
defmodule Eecrit.Router do
  use Eecrit.Web, :router
  import Eecrit.SessionPlugs, only: [add_current_user: 2,
                                     v2_add_current_user: 2,
                                     require_login: 2,
                                     require_admin: 2,
                                     require_superuser: 2]
  import Eecrit.SinglePageAppPlugs, only: [default_to_no_single_page_app: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :add_current_user
    plug :v2_add_current_user
    plug :default_to_no_single_page_app
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/v2", Eecrit do 
    pipe_through [:browser]

    get "/", V2PageController, :index
    get "/about", V2PageController, :about
    get "/experiment", V2PageController, :experiment
    resources "/sessions", V2SessionController, only: [:delete]
    get "/animals/*rest", AnimalController, :all
    post "/log_in_demo_user", V2SessionController, :log_in_demo_user
    get "/unfinished", UnfinishedController, :index

    get "/*path", ElmController, :choose_page
  end  

  # TODO: I'm not sure where to store the fact that a user must have
  # ability X to access resource Y. Should it be here, to give a broad
  # overview? Or should it be attached to the resource (which would make
  # sense for finer-granularity permissions)?
  #
  # A related issue: we need not only to prevent a pipeline from delivering
  # the user to a page, we also need views to not display links to that page.
  # So it's more than just about controllers.
  

  # Not-logged-in users
  scope "/", Eecrit do
    pipe_through :browser

    get "/", PageController, :index
    get "/help", HelpController, :index
    # TODO: Remove this when more comfortable with embedding Elm
    get "/elm", ElmController, :index
    get "/iv/*path", IVController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Only for logged-in users
  scope "/", Eecrit do
    pipe_through [:browser, :require_login]
  end

  # Controllers that require Admin permissions.
  scope "/", Eecrit do
    pipe_through [:browser, :require_login, :require_admin]

    resources "/animals", OldAnimalController
    resources "/procedures", OldProcedureController
    resources "/procedure_descriptions", OldProcedureDescriptionController

    scope "/reports" do
      get "/animal-use", ReportController, :animal_use
      post "/animal-use", ReportController, :animal_use
      get "/animal-reservations", ReportController, :animal_reservations
    end
  end

  # Controllers that require superuser permissions.
  scope "/", Eecrit do
    pipe_through [:browser, :require_login, :require_superuser]

    resources "/users", UserController
    resources "/ability_groups", AbilityGroupController
    resources "/organizations", OrganizationController
  end

  scope "/api", Eecrit do
    pipe_through :api
    
    resources "/animals", OldAnimalApiController, only: [:index]

    # Todo: how to do all the rest fakery from elm - if it's worth it
    post "/v2animals/create/:original_id", AnimalApiController, :create
    get "/v2animals", AnimalApiController, :index
    post "/v2animals", AnimalApiController, :update
    get "/v2animals/:id/history", AnimalApiController, :history
  end
end

web/models/old_procedure.ex
defmodule Eecrit.OldProcedure do
  use Eecrit.Web, :model
  use Eecrit.ModelDefaults, model: __MODULE__
  resource_requires_ability :is_admin

  alias Eecrit.Pile

  schema "procedures" do
    field :name, :string
    field :days_delay, :integer

    has_many :procedure_descriptions, Eecrit.OldProcedureDescription, foreign_key: :procedure_id
  end

  @visible_fields [:name, :days_delay]
  @fields_always_required @visible_fields

  defp changeset(struct, params) do
    struct
    |> cast(params, @visible_fields)
    |> validate_required(@fields_always_required)
  end


  ## Utility

  def alphabetical_names(procedure_list) do
    procedure_list
    |> Pile.sort_human_alphabetically(:name)
    |> Pile.extract_values(:name)
  end

end

web/controllers/old_procedure_controller.ex
defmodule Eecrit.OldProcedureController do
  use Eecrit.Web, :controller
  alias Eecrit.OldProcedure

  def index(conn, _params) do
    procedures = OldRepo.all(from a in OldProcedure,
                             order_by: fragment("lower(?)", a.name))
    render(conn, "index.html", procedures: procedures)
  end

  def new(conn, _params) do
    render_new(conn, OldProcedure.new_action_changeset)
  end

  def create(conn, %{"old_procedure" => old_procedure_params}) do
    changeset = OldProcedure.create_action_changeset(old_procedure_params)

    case OldRepo.insert(changeset) do
      {:ok, old_procedure} ->
        conn
        |> put_flash(:info, "#{old_procedure.name} was created.")
        |> redirect(to: old_procedure_path(conn, :show, old_procedure.id))
      {:error, changeset} ->
        render_new(conn, changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", old_procedure: get(id))
  end

  def edit(conn, %{"id" => id}) do
    old_procedure = get(id)
    changeset = OldProcedure.edit_action_changeset(old_procedure)
    render_edit(conn, old_procedure, changeset)
  end

  def update(conn, %{"id" => id, "old_procedure" => old_procedure_params}) do
    old_procedure = get(id)
    changeset = OldProcedure.update_action_changeset(old_procedure, old_procedure_params)

    case OldRepo.update(changeset) do
      {:ok, old_procedure} ->
        conn
        |> put_flash(:info, "#{old_procedure.name} has been changed.")
        |> redirect(to: old_procedure_path(conn, :show, old_procedure))
      {:error, changeset} ->
        render_edit(conn, old_procedure, changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    OldRepo.delete!(get(id))

    conn
    |> put_flash(:info, "Procedure deleted successfully.")
    |> redirect(to: old_procedure_path(conn, :index))
  end

  defp get(id) do 
    OldRepo.get!(OldProcedure, id) |> OldRepo.preload(:procedure_descriptions)
  end
  
  defp render_new(conn, changeset) do
    render(conn, "new.html", changeset: changeset)
  end

  defp render_edit(conn, old_procedure, changeset) do
    render(conn, "edit.html", old_procedure: old_procedure, changeset: changeset)
  end
end

web/views/old_procedure_view.ex
defmodule Eecrit.OldProcedureView do
  use Eecrit.Web, :view
end

web/templates/old_procedure/edit.html.eex
<h2>Edit <%= @old_procedure.name %></h2>

<p>To edit one of the procedure's per-species descriptions,
  <%= link "show them all",
      to: old_procedure_path(@conn, :show, @old_procedure.id),
      class: "btn btn-default" %>
  and choose one there.</p>


<%= render "form.html", changeset: @changeset,
                        action: old_procedure_path(@conn, :update, @old_procedure) %>

Or abandon editing in one of these two ways:

<div class="input-group">
  <span class="input-group-btn">
    <%= link "Show #{@old_procedure.name}",
        to: old_procedure_path(@conn, :show, @old_procedure),
        class: "btn btn-default" %>
    <%= link "Show all procedures",
        to: old_procedure_path(@conn, :index),
        class: "btn btn-default" %>
  </span>
</div>

web/templates/old_procedure/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= error_tag f, :name %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :days_delay, class: "control-label" %>
    <%= error_tag f, :days_delay %>
    <%= number_input f, :days_delay, value: Map.get(@changeset.data, :days_delay) || 0, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/old_procedure/index.html.eex
<h2>Procedures</h2>

<div class="input-group">
  <span class="input-group-btn">
<%= link "Add new procedure", to: old_procedure_path(@conn, :new), class: "btn btn-default" %>
  </span>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Days delay</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for old_procedure <- @procedures do %>
    <tr>
      <td><%= old_procedure.name %></td>
      <td><%= old_procedure.days_delay %></td>

      <td class="text-right">
        <%= link "Show", to: old_procedure_path(@conn, :show, old_procedure), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: old_procedure_path(@conn, :edit, old_procedure), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: old_procedure_path(@conn, :delete, old_procedure), method: :delete, data: [confirm: "Are you sure? DO NOT delete a procedure that has ever been used in a reservation."], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<div class="input-group">
  <span class="input-group-btn">
<%= link "Add new procedure", to: old_procedure_path(@conn, :new), class: "btn btn-default" %>
  </span>
</div>

web/templates/old_procedure/new.html.eex
<h2>New procedure</h2>

<p>You will be able to add species-specific descriptions of the
procedure after you click SUBMIT. </p>

<%= render "form.html", changeset: @changeset,
                        action: old_procedure_path(@conn, :create) %>

<%= link "Back to procedure list", to: old_procedure_path(@conn, :index), class: "btn btn-default" %>

web/templates/old_procedure/show.html.eex
<h2><%= String.capitalize(@old_procedure.name) %></h2>

<ul>
  <li>
    <strong>Days delay:</strong>
    <%= @old_procedure.days_delay %>
  </li>

</ul>

<div class="input-group">
  <span class="input-group-btn">
    <%= link "Add a description", to: old_procedure_description_path(@conn, :new, procedure: @old_procedure.id), class: "btn btn-default" %>
    <%= link "Change the name or delay", to: old_procedure_path(@conn, :edit, @old_procedure), class: "btn btn-default" %>
    <%= link "Show all procedures", to: old_procedure_path(@conn, :index), class: "btn btn-default" %>
  </span>
</div>

<table class="table">
  <tbody>
<%= for description <- @old_procedure.procedure_descriptions do %>
    <tr>
      <td><%= raw(description.description) %></td>
      <td>
        <%= link "Edit this description",
            to: old_procedure_description_path(@conn, :edit, description, procedure: @old_procedure.id),
            class: "btn btn-default" %>
        <%= link "Delete", to: old_procedure_description_path(@conn, :delete, description), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>