web/router.ex
defmodule Eecrit.Router do
  use Eecrit.Web, :router
  import Eecrit.SessionPlugs, only: [add_current_user: 2,
                                     v2_add_current_user: 2,
                                     require_login: 2,
                                     require_admin: 2,
                                     require_superuser: 2]
  import Eecrit.SinglePageAppPlugs, only: [default_to_no_single_page_app: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :add_current_user
    plug :v2_add_current_user
    plug :default_to_no_single_page_app
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/v2", Eecrit do 
    pipe_through [:browser]

    get "/", V2PageController, :index
    get "/about", V2PageController, :about
    get "/experiment", V2PageController, :experiment
    resources "/sessions", V2SessionController, only: [:delete]
    get "/animals/*rest", AnimalController, :all
    post "/log_in_demo_user", V2SessionController, :log_in_demo_user
    get "/unfinished", UnfinishedController, :index

    get "/*path", ElmController, :choose_page
  end  

  # TODO: I'm not sure where to store the fact that a user must have
  # ability X to access resource Y. Should it be here, to give a broad
  # overview? Or should it be attached to the resource (which would make
  # sense for finer-granularity permissions)?
  #
  # A related issue: we need not only to prevent a pipeline from delivering
  # the user to a page, we also need views to not display links to that page.
  # So it's more than just about controllers.
  

  # Not-logged-in users
  scope "/", Eecrit do
    pipe_through :browser

    get "/", PageController, :index
    get "/help", HelpController, :index
    # TODO: Remove this when more comfortable with embedding Elm
    get "/elm", ElmController, :index
    get "/iv/*path", IVController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Only for logged-in users
  scope "/", Eecrit do
    pipe_through [:browser, :require_login]
  end

  # Controllers that require Admin permissions.
  scope "/", Eecrit do
    pipe_through [:browser, :require_login, :require_admin]

    resources "/animals", OldAnimalController
    resources "/procedures", OldProcedureController
    resources "/procedure_descriptions", OldProcedureDescriptionController

    scope "/reports" do
      get "/animal-use", ReportController, :animal_use
      post "/animal-use", ReportController, :animal_use
      get "/animal-reservations", ReportController, :animal_reservations
    end
  end

  # Controllers that require superuser permissions.
  scope "/", Eecrit do
    pipe_through [:browser, :require_login, :require_superuser]

    resources "/users", UserController
    resources "/ability_groups", AbilityGroupController
    resources "/organizations", OrganizationController
  end

  scope "/api", Eecrit do
    pipe_through :api
    
    resources "/animals", OldAnimalApiController, only: [:index]

    # Todo: how to do all the rest fakery from elm - if it's worth it
    post "/v2animals/create/:original_id", AnimalApiController, :create
    get "/v2animals", AnimalApiController, :index
    post "/v2animals", AnimalApiController, :update
    get "/v2animals/:id/history", AnimalApiController, :history
  end
end

web/controllers/report_controller.ex
defmodule Eecrit.ReportController do
  use Eecrit.Web, :controller
  alias Eecrit.AnimalUseReportTxs
  alias Eecrit.AnimalReservationReportTxs
  alias Eecrit.ViewModel

  def animal_use(conn, %{"report" => params}) do
    %{"first_date" => first_date, "last_date" => last_date} = params
    view_model = AnimalUseReportTxs.run({first_date, last_date})
    date_range = ViewModel.date_range({first_date, last_date})
    render(conn, "animal_use.html", view_model: view_model, input_data: date_range)
  end

  def animal_use(conn, _params) do
    render(conn, "animal_use_new.html")
  end

  def animal_reservations(conn,
    %{"animal" => id, "first_date" => first_date,  "last_date" => last_date}) do
    view_model = AnimalReservationReportTxs.run(id,
      date_range: {first_date, last_date})
    render(conn, "animal_reservations.html", view_model: view_model)
  end
end

web/views/report_view.ex
defmodule Eecrit.ReportView do
  use Eecrit.Web, :view
end

web/templates/report/animal_reservations.html.eex
<h3>
  Reservations for <%= VMP.link_to_more_detail(@view_model.animal, @conn) %>
  <%= ModelDisplays.date_range(@view_model.date_range) %>
</h3>

(Note: reservations may overlap the beginning or end of the date range. For example, a three day reservation that starts the day before
<%= ModelDisplays.date(@view_model.date_range.first_date) %> will be shown.)

<table class="table table-striped table-condensed">
  <tbody>
  <%= for reservation <- @view_model.reservations do %>
    <tr>
      <td>
        <%= ModelDisplays.date_range_without_prefix(reservation.date_range) %>:
        <%= ModelDisplays.times(reservation.time_bits)%>
      </td>

      <td>
        <%= reservation.instructor %> for <%= reservation.course %>
      </td>
      <td>
        <ul>
          <%= for procedure <- reservation.procedures do %>
              <li>
                <%= VMP.link_to_more_detail(procedure, @conn) %>
              </li>
          <% end %>
        </ul>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

web/templates/report/animal_use.html.eex
<h2>Animal Use Report</h2>

<%= render "date_range.html", conn: @conn, action: report_path(@conn, :animal_use) %>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Animal</th>
      <th>Uses</th>
    </tr>
  </thead>
  <tbody>
  <%= for [animal | procedures] <- @view_model do %>
    <tr>
      <td><%= VMP.link_to_more_detail(animal, @conn) %></td>
      <td>
        <ul>
          <%= for procedure <- procedures do %>
              <li>
                <%= VMP.link_to_more_detail(procedure, @conn) %>
                (<%= procedure.use_count %>)
              </li>
          <% end %>
        </ul>
      </td>
      <td>
        <%= ModelDisplays.animal_resources(@conn, animal.id, 
            @input_data.first_date, @input_data.last_date) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

web/templates/report/animal_use_new.html.eex
<h2>Animal Use Report</h2>

<%= render "date_range.html", conn: @conn, action: report_path(@conn, :animal_use) %>

web/templates/report/date_range.html.eex
<%= form_for @conn, @action, [as: "report"], fn f -> %>
  <div class="form-group">
    <%= label f, "Report dates (inclusive)", class: "control-label" %>
    <%= error_tag f, :date_removed_from_service %>

    <div class="input-group input-daterange" data-provide="datepicker">
      <%= text_input f, :first_date, class: "form-control" %>
      <span class="input-group-addon">to</span>
      <%= text_input f, :last_date, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>